eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: default-zone
    service-url:
      default-zone: http://192.168.1.66:8761/eureka/
  instance:
    hostname: 192.168.1.66
