eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: default-zone
    service-url:
      default-zone: http://registry:8761/eureka/
  instance:
    hostname: registry
